/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BodySchema {
  age: number;
  dependents: number;
  income: number;
  marital_status: "single" | "married";
  risk_questions: [number, number, number];
  house?: {
    ownership_status: "owned" | "mortgaged";
    [k: string]: unknown;
  };
  vehicle?: {
    year: number;
    [k: string]: unknown;
  };
}
